#CodeDeploy 설정 파일
version: 0.0
os: linux
files:
  - source: / #이동 대상. 루트(/)는 전체 파일
    destination: /home/ec2-user/app3/myblog/zip/ #목적지. 무중단 배포 app -> app3 변경
    overwrite: yes #덮어쓰기

#CodeDeploy가 EC2 서버로 넘긴 파일 권한    
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

#CodeDeploy 배포 단계에서 실행할 명령어 지정
hooks:
  AfterInstall:
    - location: stop.sh #엔진엑스와 연결되어 있지 않은 스프링 부트 종료
      timeout: 120
      runas: root

  ApplicationStart:
    - location: start.sh #엔진엑스와 연결되어 있지 않은 Port로 새 버전 스프링 부트 연결
      timeout: 120
      runas: root

  ValidateService:
    - location: health.sh #새 스프링 부트가 정상 연결되었는지 확인
      timeout: 120
      runas: root