#CodeDeploy 설정 파일
version: 0.0
os: linux
files:
  - source: / #이동 대상. 루트(/)는 전체 파일
    destination: /home/ec2-user/app/myblog/zip/ #목적지
    overwrite: yes #덮어쓰기

#CodeDeploy가 EC2 서버로 넘긴 파일 권한    
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

#CodeDeploy 배포 단계에서 실행할 명령어 지정
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 120
      runas: ec2-user
